# -*- coding: utf-8 -*-
"""tirgul4_1Cloud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q49woLvLRFUnzt2LSEHYmH7KpWT8fMWK
"""

from google.colab import drive
drive.mount("/content/drive/")

# -*- coding: utf-8 -*-
"""Cars_DB.ipynb
.
Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vX90dk7RUqXPNgH-kMnnTPhtwSaDCRUs
"""

url = 'https://data.gov.il/api/3/action/datastore_search?resource_id=053cea08-09bc-40ec-8f7a-156f0677aff3'

import requests
import pandas as pd
pd.set_option("display.max_columns", None)

response = requests.get(url)
data = response.json()
df = pd.DataFrame(data)

data_df = pd.DataFrame(data['result']['records'])

data_df.head()

# Import necessary libraries
from ipywidgets import widgets, VBox, interact, Output
from IPython.display import display
output_area = Output()

# Create widgets
tozeret_nm_dropdown = widgets.Dropdown(
    options=[''] + sorted(data_df['tozeret_nm'].unique().tolist()),
    description='Tozeret:',
    style={'description_width': 'initial'}
)

kinuy_mishari_dropdown = widgets.Dropdown(
    options=[''],
    description='Kinuy Mishari:',
    style={'description_width': 'initial'}
)

# Function to update the second dropdown based on the selection of the first
def update_kinuy_mishari_options(change):
    if change['new']:  # Check if a valid option is selected
        filtered_values = data_df[data_df['tozeret_nm'] == change['new']]['kinuy_mishari'].unique()
        kinuy_mishari_dropdown.options = [''] + sorted(filtered_values)
    else:
        kinuy_mishari_dropdown.options = ['']

# Function to update the output area with the total records and unique 'ramat_gimur' values
def update_output(change=None):
    output_area.clear_output()
    selected_tozeret = tozeret_nm_dropdown.value
    selected_kinuy = kinuy_mishari_dropdown.value

    if selected_tozeret and selected_kinuy:
        filtered_df = data_df[
            (data_df['tozeret_nm'] == selected_tozeret) &
            (data_df['kinuy_mishari'] == selected_kinuy)
        ]
        total_records = len(filtered_df)
        unique_ramat_gimur = filtered_df['ramat_gimur'].unique()

        with output_area:
            print(f"Total Records: {total_records}")
            print(f"Unique Ramat Gimur: {', '.join(unique_ramat_gimur) if len(unique_ramat_gimur) > 0 else 'None'}")
    else:
        with output_area:
            print("Please select valid options for both dropdowns.")

# Observe changes in both dropdowns
tozeret_nm_dropdown.observe(update_kinuy_mishari_options, names='value')
kinuy_mishari_dropdown.observe(update_output, names='value')

# Display widgets and output area
display(VBox([tozeret_nm_dropdown, kinuy_mishari_dropdown, output_area]))

# import json
# data = {"variable-1": 1.0,"variable-2": 4.5, "variable-3": 2.3, "variable-4": 1.4, "variable-5": 1.3}
# with open("/content/drive/MyDrive/Colab Notebooks/Cloud/3_1.json", "w") as f:
#     json.dump(data, f, indent=4)

import matplotlib.pyplot as plt
import json

dictionary = json.load(open('/content/drive/MyDrive/Colab Notebooks/Cloud/3_1.json', 'r'))
xAxis = [key for key, value in dictionary.items()]
yAxis = [value for key, value in dictionary.items()]
plt.grid(True)

## LINE GRAPH ##
plt.plot(xAxis,yAxis, color='#8a5082', marker='o')
plt.xlabel('variable')
plt.ylabel('value')

plt.show()

# Importing the matplotlib library
import matplotlib.pyplot as plt
# Categorical data: Country names
countries = ['USA', 'Brazil', 'Russia', 'Spain', 'UK', 'India']
# Integer value interms of death counts
totalDeaths = [112596, 37312, 5971, 27136, 40597, 7449]
# Passing the parameters to the bar function, this is the main function which creates the bar plot
plt.bar(countries, totalDeaths)
# Displaying the bar plot
plt.show()

import pandas as pd
a = [1, 7, 2]
myvar = pd.Series(a)
print(myvar)
print('-------------')
print(myvar[0])

import pandas as pd
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

import pandas as pd
data = {
"calories": [420, 380, 390],
"duration": [50, 40, 45]
}

myvar2 = pd.DataFrame(data, index = ["day1", "day2", "day3"])
print(myvar2)

import pandas as pd
data = {
"calories": [420, 380, 390],
"duration": [50, 40, 45]
}
df = pd.DataFrame(data, index = ["day1", "day2", "day3"])
print(df)
print('----------------')
#refer to the named index:
print(df.loc["day2"])

import pandas
mydataset = {
 'cars': ["BMW", "Volvo", "Ford"],
 'passings': [3, 7, 2]
}
myvar = pandas.DataFrame(mydataset)
print(myvar)
myvar.to_json("3_2.json")

import json
data = {
  "cars": ["BMW", "Volvo", "Ford"],
  "passings": [3, 7, 2]
}

# with open("/content/drive/MyDrive/Colab Notebooks/Cloud/3_2.json", "w") as f:
#     json.dump(data, f, indent=4)

import pandas as pd
df2 = pd.read_json('/content/drive/My Drive/Colab Notebooks/Cloud/3_2.json')
print(df2.to_string())

import pandas as pd

data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409.1,
    "1":479.0,
    "2":340.0,
    "3":282.4,
    "4":406.0,
    "5":300.5
  }
}
with open("/content/drive/MyDrive/Colab Notebooks/Cloud/3_3.json", "w") as f:
    json.dump(data, f, indent=4)

df = pd.DataFrame(data)

print(df)

import pandas as pd
df2 = pd.read_json('/content/drive/My Drive/Colab Notebooks/Cloud/3_3.json')
print(df2.to_string())

import pandas as pd
mydataset = {
 'cars': ['BMW','Volvo', 'Ford'],
 'passings': [3,7,2]
}
df = pd.DataFrame(mydataset)
print(df)
print()
df = pd.DataFrame(mydataset)
print(df[df['passings']>5])
print()
print(df[(df['passings']>5) | (df['cars']=='Ford')])

df[df['passings']>5]

df[(df['passings']>5) | (df['cars']=='Ford')]



url = 'https://data.gov.il/api/3/action/datastore_search?resource_id=053cea08-09bc-40ec-8f7a-156f0677aff3'
import requests
import pandas as pd
pd.set_option("display.max_columns", None)
response = requests.get(url)
data = response.json()
df = pd.DataFrame(data)

data_df = pd.DataFrame(data['result']['records'])
#יציג את 5 השורות הראשונות של הנתונים

data_df.head()

url = 'https://data.gov.il/api/3/action/datastore_search?resource_id=053cea08-09bc-40ec-8f7a-156f0677aff3'
Tozeret = "" # @param [""]
Kinuy_Mishari = "" # @param [""]

import requests
import pandas as pd
pd.set_option("display.max_columns", None)
response = requests.get(url)
data = response.json()
df = pd.DataFrame(data)


# Create a DataFrame from the 'records' in the JSON response
data_df = pd.DataFrame(data['result']['records'])

# Set Tozeret with the 'tozeret_nm' column values
print (data_df['tozeret_nm'].tolist())

import matplotlib.pyplot as plt
import json
from google.colab import drive
drive.mount('/content/drive')
dictionary = json.load( open('/content/drive/My Drive/Colab Notebooks/Cloud/3_1.json' , 'r'))
xAxis = [key for key, value in dictionary.items()]
yAxis = [value for key, value in dictionary.items()]
plt.grid(True)
## LINE GRAPH ##
plt.plot(xAxis,yAxis, color= '#8a5082', marker='o')
plt.xlabel( 'variable')
plt.ylabel( 'value')
plt.show()



#CREATING WITH TABS

import pandas as pd
import ipywidgets as widgets
from IPython.display import display
from plotly.offline import iplot
import plotly.graph_objs as go
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns  #seaborn for heatmap


# Create a simple DataFrame
# data = {
#     'Name': ['Alice', 'Bob', 'Charlie'],
#     'Age': [25, 30, 35],
#     'City': ['New York', 'Los Angeles', 'Chicago']
# }
# df = pd.DataFrame(data)
print(data_df)

# Tab 1: Data Overview
tab1_content = widgets.Output()
with tab1_content:
    print("Data Overview:")
    display(data_df.describe())  # Summary statistics

# Tab 2: Raw Data
tab2_content = widgets.Output()
with tab2_content:
    print("Raw Data:")
    display(data_df)  # Full DataFrame

# Tab 3: Charts
tab3_content = widgets.Output()
with tab3_content:
    print("Charts:")
    plt.clf()  # Clear the current figure
    plt.figure(figsize=(10, 8))  # Increased figure size to accommodate labels
    side_length = 10
    xAxis =  set(data_df['shnat_yitzur'])
    xAxis = list(xAxis)
    yAxis = data_df['shnat_yitzur'].value_counts().tolist()
    plt.grid(True)
    ## LINE GRAPH ##
    plt.plot(xAxis,yAxis, color= '#8a5082', marker='o')
    plt.xlabel('Years')
    plt.ylabel('Created cars')
    plt.show()  # Add this to display the plot
    plt.close()  # Close the figure t free memory

# Create Tabs
tabs = widgets.Tab(children=[tab1_content, tab2_content,tab3_content])
tabs.set_title(0, 'Tab 1: Data Overview')
tabs.set_title(1, 'Tab 2: Raw Data')
tabs.set_title(2, 'Tab 3: Charts')



# Display Tabs
display(tabs)